ASPNetCase1/src/ASPNetCase1/ViewModels/RegisterViewModel.cs
using System.ComponentModel.DataAnnotations;
namespace ASPNetCase1.ViewModels
{
    public class RegisterViewModel
    {
        public string UserName { get; set; }
        [Required(ErrorMessage = "Firstname is required.")]
        public string Firstname { get; set; }
        [Required(ErrorMessage = "Lastname is required.")]
        public string Lastname { get; set; }
        [Required(ErrorMessage = "Password is required.")]
        public string Password { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        [CompareAttribute("Password", ErrorMessage = "Passwords don't match.")]
        public string RepeatPassword { get; set; }
        [Required(ErrorMessage = "Age is required")]
        [Range(18, 99)]
        public int Age { get; set; }
        [Required(ErrorMessage = "Email is required.")]
        [EmailAddress(ErrorMessage = "email needs valid format")]
        [Display(Name = "Email")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Street address is required.")]
        public string Address1 { get; set; }
        [Required(ErrorMessage = "City is required.")]
        public string City { get; set; }
        [RegularExpression(@"[a-zA-z]\d[a-zA-Z]-\d[a-zA-Z]\d", ErrorMessage = "Invalid format")]
        [Required(ErrorMessage = "Enter a proper Postal Code")]
        public string Mailcode { get; set; }
        [Required(ErrorMessage = "Country is required.")]
        public string Country { get; set; }
        [Required(ErrorMessage = "Credit Card is required.")]
        public string CreditcardType { get; set; }
        [Required(ErrorMessage = "Region is required.")]
        public string Region { get; set; }
    }
}

ASPNetCase1/src/ASPNetCase1/Controllers/RegisterController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Identity;
using ASPNetCase1.Models;
using Microsoft.AspNet.Http;
using ASPNetCase1.ViewModels;
using ASPNetCase1.Utils;
using Microsoft.AspNet.Authorization;

namespace ASPNetCase1.Controllers
{
    public class RegisterController : Controller
    {
        UserManager<ApplicationUser> _usrMgr;
        SignInManager<ApplicationUser> _signInMgr;
        public RegisterController(UserManager<ApplicationUser> userManager,
        SignInManager<ApplicationUser> signInManager)
        {
            _usrMgr = userManager;
            _signInMgr = signInManager;
        }
        // GET: Products
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View();
        }
        //
        // POST:/Register/Register
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Register/Register")]
        [AllowAnonymous]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser {
                    UserName = model.Email,
                    Email = model.Email,
                    Firstname = model.Firstname,
                    Lastname = model.Lastname,
                    Age = model.Age,
                    Address1 = model.Address1,
                    City = model.City,
                    Mailcode = model.Mailcode,
                    Country = model.Country,
                    CreditcardType = model.CreditcardType,
                    Region = model.Region};
                var result = await _usrMgr.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    await _signInMgr.SignInAsync(user, isPersistent: false);
                    HttpContext.Session.SetString(SessionVars.LoginStatus, "logged on as " + model.Email);
                    HttpContext.Session.SetString(SessionVars.Message, "Registered, as " + model.Email);
                }
                else
                {
                    ViewBag.Message = "registration failed - " + result.Errors.First().Description;
                    return View("Index");
                }
            }
            return Redirect("/Home");
        }
    }
}

ASPNetCase1/src/ASPNetCase1/Views/Register/Index.cshtml
@model RegisterViewModel
<div class="text-center padTop10">
    <h6>&copy; - 2016</h6>
    <br />
    <h4>@ViewBag.Message</h4>
</div>
<!-- modal code -->
<div class="modal" id="register_popup">
    <div class="modal-dialog">
        <div class="modal-content col-xs-12">
            <div class="modal-header">
                <a href="" style="font-size:xx-large" data-dismiss="modal" class="pull-right">X</a>
                <div class="text-center">
                    <h3 class="title">Please Register!</h3>
                </div>
            </div>
            <div class="modal-body loginbody">
                <form asp-controller="Register" asp-action="Register" method="post" class="form-horizontal" role="form">
                    <div class="tabbable" id="myTabs">
                        <ul class="nav nav-tabs">
                            <li class="active"><a href="#personal" data-toggle="tab">Demographic</a></li>
                            <li><a href="#address" data-toggle="tab">Address</a></li>
                            <li><a href="#account" data-toggle="tab">Account</a></li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="personal">
                                <div class="form-group" style="padding-left:5%;padding-top:5%;">
                                    <label asp-for="Firstname" class="col-xs-4 control-label"></label>
                                    <div class="col-xs-7" style="padding-left:5%;">
                                        <input asp-for="Firstname" class="form-control" placeholder="First Name" />
                                        <span asp-validation-for="Firstname" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group" style="padding-left:5%;">
                                    <label asp-for="Lastname" class="col-xs-4 control-label"></label>
                                    <div class="col-xs-7" style="padding-left:5%;">
                                        <input asp-for="Lastname" class="form-control" placeholder="Last Name" />
                                        <span asp-validation-for="Lastname" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group" style="padding-left:5%;">
                                    <label asp-for="Age" class="col-xs-4 control-label"></label>
                                    <div class="col-xs-7" style="padding-left:5%;">
                                        <input asp-for="Age" type="number" class="form-control" placeholder="Age" />
                                        <span asp-validation-for="Age" class="text-danger"></span>
                                    </div>
                                </div>

                                <div class="form-group" style="padding-left:5%;">
                                    <label asp-for="CreditcardType" class="col-xs-4 control-label"></label>
                                    <div class="col-xs-7" style="padding-left:5%;">
                                        <select asp-for="CreditcardType" type="" class="form-control">
                                            <option selected disabled hidden style='display: none' value=''></option>
                                            <option value="visa">Visa</option>
                                            <option value="masterCard">MasterCard</option>
                                         </select>
                                        
                                        <span asp-validation-for="CreditcardType" class="text-danger"></span>
                                    </div>
                                </div>
                            </div> @*END PERSONAL TAB*@
                            <div class="tab-pane" id="address">
                                <div class="form-group" style="padding-top:5%;">
                                    <label asp-for="Address1" class="col-xs-4 control-label"></label>
                                    <div class="col-xs-7" style="padding-left:5%;">
                                        <input asp-for="Address1" class="form-control" placeholder="Enter Address" />
                                        <span asp-validation-for="Address1" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Mailcode" class="col-xs-4 control-label"></label>
                                    <div class="col-xs-7" style="padding-left:5%;">
                                        <input asp-for="Mailcode" class="form-control" placeholder="Postal Code (n1n-1n1)" />
                                        <span asp-validation-for="Mailcode" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label asp-for="City" class="col-xs-4 control-label"></label>
                                    <div class="col-xs-7" style="padding-left:5%;">
                                        <input asp-for="City" class="form-control" placeholder="Enter City" />
                                        <span asp-validation-for="City" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Region" class="col-xs-4 control-label"></label>
                                    <div class="col-xs-7" style="padding-left:5%;">
                                        <input asp-for="Region" class="form-control" placeholder="Enter Region (eg. On)" />
                                        <span asp-validation-for="Region" class="text-danger"></span>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label asp-for="Country" class="col-xs-4 control-label"></label>
                                    <div class="col-xs-7" style="padding-left:5%;">
                                        <select asp-for="Country" class="form-control">
                                            <option selected disabled hidden style='display: none' value=''></option>
                                            <option value="canada">Canada</option>
                                            <option value="usa">USA</option>
                                            <option value="mexico">Mexico</option>
                                            <option value="sweden">Sweden</option>
                                            <option value="finland">Finland</option>
                                            <option value="venezuela">Venezuela</option>
                                        </select>
                                        <span asp-validation-for="Country" class="text-danger"></span>
                                    </div>
                                </div>
                            </div> @*END ADDRESS TAB*@
                            <div class="tab-pane" id="account">
                                <div class="form-group" style="padding-top:5%;">
                                    <label asp-for="Email" class="col-xs-4 control-label"></label>
                                    <div class="col-xs-7" style="padding-left:5%;">
                                        <input asp-for="Email" type="email" class="form-control" placeholder="Enter valid Email" />
                                        <span asp-validation-for="Email" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Password" class="col-xs-4 control-label"></label>
                                    <div class="col-xs-7" style="padding-left:5%;">
                                        <input asp-for="Password" type="password" class="form-control" placeholder="Enter password" />
                                        <span asp-validation-for="Password" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label asp-for="RepeatPassword" class="col-xs-4 control-label">Repeat PW</label>
                                    <div class="col-xs-7" style="padding-left:5%;">
                                        <input asp-for="RepeatPassword" type="password" class="form-control" placeholder="Enter same password" />
                                        <span asp-validation-for="RepeatPassword" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-xs-12 text-center">
                                        <button type="submit" class="btn btn-default">Register</button>
                                    </div>
                                </div>
                            </div> @*END ACCOUNT TAB*@
                        </div>
                    </div>
                </form>
            </div><!-- modal-body -->
            <div class="modal-footer">
                <br />
                @ViewBag.Message
            </div><!-- modal-footer-->
        </div><!--modal-content-->
    </div><!--modal-dialog-->
</div><!--modal-->