ASPNetCase1/src/ASPNetCase1/ViewModels/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;
namespace ASPNetCase1.ViewModels
{
    public class LoginViewModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

ASPNetCase1/src/ASPNetCase1/Controllers/LoginController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Http;
using ASPNetCase1.Models;
using ASPNetCase1.ViewModels;
using ASPNetCase1.Utils;
using Microsoft.AspNet.Authorization;

namespace ASPNetCase1.Controllers
{
    public class LoginController : Controller
    {
        UserManager<ApplicationUser> _usrMgr;
        SignInManager<ApplicationUser> _signInMgr;
        public LoginController(UserManager<ApplicationUser> userManager,
        SignInManager<ApplicationUser> signInManager)
        {
            _usrMgr = userManager;
            _signInMgr = signInManager;
        }
        // GET: Login
        [AllowAnonymous]
        public ActionResult Index(string ReturnUrl = null)
        {
            if (HttpContext.Session.Get(SessionVars.LoginStatus) == null)
            {
                HttpContext.Session.SetString(SessionVars.LoginStatus, "not logged in");
            }
            if (Convert.ToString(HttpContext.Session.Get(SessionVars.LoginStatus)) == "not logged in")
            {
                HttpContext.Session.SetString(SessionVars.Message, "most functionality requires you to login!");
            }
            ViewBag.Status = HttpContext.Session.GetString(SessionVars.LoginStatus);
            ViewBag.Message = HttpContext.Session.GetString(SessionVars.Message);
            ViewBag.ReturnUrl = ReturnUrl;
            return View();
        }
        private IActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            else
            {
                return Redirect("/Home");
            }
        }
        //
        // POST: /Account/Login
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginViewModel model, string returnUrl = null)
        {
            ViewBag.ReturnUrl = returnUrl;
            if (ModelState.IsValid)
            {
                // This doesn't count login failures towards account lockout
                // To enable password failures to trigger account lockout, set lockoutOnFailure: true
                var result = await _signInMgr.PasswordSignInAsync(model.Email, model.Password, isPersistent: false, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    HttpContext.Session.SetString(SessionVars.User, model.Email);
                    HttpContext.Session.SetString(SessionVars.LoginStatus, "logged in as " + model.Email);
                    HttpContext.Session.SetString(SessionVars.Message, "Welcome " + model.Email);
                    return RedirectToLocal(returnUrl);
                }
                else
                {
                    HttpContext.Session.SetString(SessionVars.Message, "login attempt failed");
                    ViewBag.Message = HttpContext.Session.GetString(SessionVars.Message);
                    return View("Index");
                }
            }
            // If we got this far, something failed, redisplay form
            return RedirectToLocal(returnUrl);
        }
        public async Task<IActionResult> LogOff(string returnUrl = null)
        {
            await _signInMgr.SignOutAsync();
            HttpContext.Session.Clear();
            HttpContext.Session.SetString(SessionVars.LoginStatus, "not logged in");
            return Redirect("/Home");
        }
    }
}

ASPNetCase1/src/ASPNetCase1/Views/Login/Index.cshtml
@model LoginViewModel
<div class="col-lg-4"></div>
<div class="col-lg-4 text-center padTop10">
    <h6>&copy; - 2016</h6>
    <br />
    <h4>@ViewBag.Status</h4>
</div>
<div class="modal" id="login_popup" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content col-xs-12">
            <a href="" style="font-size:xx-large" data-dismiss="modal" class="pull-right" aria-hidden="true">X</a>
            <div class="text-center">
                <h3 class="title">Please Login!</h3>
            </div>
            <div class="modal-body">
                <section>
                    <form asp-controller="Login" asp-action="Login" asp-route-returnurl="@ViewBag.ReturnUrl" method="post" class="form-horizontal" role="form">
                        <div class="form-group" style="padding-left:5%;">
                            <label asp-for="Email" class="col-xs-4 control-label">Email:</label>
                            <div class="col-xs-7">
                                <input asp-for="Email" class="form-control" />
                                <span asp-validation-for="Email" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group" style="padding-left:5%;">
                            <label asp-for="Password" class="col-xs-4 control-label">Password:</label>
                            <div class="col-xs-7">
                                <input asp-for="Password" class="form-control" />
                                <span asp-validation-for="Password" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group col-xs-12 text-center">
                            <div style="padding-top:5%;" class="text-center">
                                <button type="submit" class="btn btn-default text-center">Log in</button>
                            </div>
                        </div>
                    </form>
                </section>
                <div class="modal-footer">
                    <br />
                    <div class="text-center">
                        @ViewBag.Message
                    </div>
                </div>
            </div>
        </div><!--modal-content-->
    </div><!--modal-dialog-->
</div><!--modal-->