ASPNetCase1/src/ASPNetCase1/Models/Genre.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ASPNetCase1.Models
{
    public class Genre
    {
        public Genre()
        {
            Products = new HashSet<Product>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int GenreId { get; set; }
        [Required]
        [StringLength(200)]
        public string Name { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}

ASPNetCase1/src/ASPNetCase1/ViewModels/GenreViewModel.cs
using Microsoft.AspNet.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using ASPNetCase1.Models;
namespace ASPNetCase1.ViewModels
{
    public class GenreViewModel
    {
        public GenreViewModel() { }
        public string GenreName { get; set; }
        public List<Genre> Genres { get; set; }
        public IEnumerable<Product> Products { get; set; }
        public IEnumerable<SelectListItem> GetGenreNames()
        {
            return Genres.Select(genre => new SelectListItem { Text = genre.Name, Value = genre.Name });
        }
    }
}

ASPNetCase1/src/ASPNetCase1/Controllers/GenreController.cs
using Microsoft.AspNet.Mvc;
using ASPNetCase1.Models;
using ASPNetCase1.ViewModels;
using Microsoft.AspNet.Http;
using System.Collections.Generic;
using System;
using ASPNetCase1.Utils;
namespace ASPNetCase1.Controllers
{
    public class GenreController : Controller
    {
        AppDbContext _db;
        public GenreController(AppDbContext context)
        {
            _db = context;
        }
        public IActionResult Index()
        {
            CatalogueViewModel vm = new CatalogueViewModel();
            // only build the catalogue once
            if (HttpContext.Session.GetObject<List<Genre>>(SessionVars.Genres) == null)
            {
                try
                {
                    GenreModel genModel = new GenreModel(_db);
                    // now load the categories
                    List<Genre> genres = genModel.GetAll();
                    HttpContext.Session.SetObject(SessionVars.Genres, genres);
                    vm.SetGenres(HttpContext.Session.GetObject<List<Genre>>(SessionVars.Genres));
                }
                catch (Exception ex)
                {
                    ViewBag.Message = "Catalogue Problem - " + ex.Message;
                }
            }
            else
            {
                vm.SetGenres(HttpContext.Session.GetObject<List<Genre>>(SessionVars.Genres));
            }
            return View(vm);
        }
        public IActionResult SelectGenre(CatalogueViewModel vm)
        {
            GenreModel genModel = new GenreModel(_db);
            AuthorModel autModel = new AuthorModel(_db);
            PublisherModel pubModel = new PublisherModel(_db);
            ProductModel catalogueModel = new ProductModel(_db);
            List<Product> items = catalogueModel.GetAllByGenreId(vm.GenreId);
            List<ProductViewModel> vms = new List<ProductViewModel>();
            if (items.Count > 0)
            {
                foreach (Product item in items)
                {
                    ProductViewModel pvm = new ProductViewModel();
                    pvm.Qty = 0;
                    pvm.ProductName = item.ProductName;
                    pvm.GenreId = item.GenreId;
                    pvm.GenreName = genModel.GetGenreName(item.GenreId);
                    pvm.Description = item.Description;
                    pvm.ProductId = item.ProductId;
                    pvm.AuthorId = item.AuthorId; //Author and pub id may be unnecessary if name is retrieved here (unless sorting/searching through them becomes possible)
                    pvm.AuthorName = autModel.GetAuthorName(item.AuthorId);
                    pvm.PublisherId = item.PublisherId;
                    pvm.PublisherName = pubModel.GetPublisherName(item.PublisherId);
                    pvm.CostPrice = Convert.ToDecimal(item.CostPrice);
                    pvm.MSRP = Convert.ToDecimal(item.MSRP);
                    pvm.GraphicName = item.GraphicName;
                    pvm.QtyOnHand = item.QtyOnHand;
                    pvm.QtyOnBackOrder = item.QtyOnBackOrder;
                    pvm.ISBN10 = item.ISBN10;
                    pvm.ISBN13 = item.ISBN13;
                    vms.Add(pvm);
                }
                ProductViewModel[] myCatalogue = vms.ToArray();
                HttpContext.Session.SetObject(SessionVars.Catalogue, myCatalogue);
            }
            vm.SetGenres(HttpContext.Session.GetObject<List<Genre>>(SessionVars.Genres));
            return View("Index", vm);
        }
        [HttpPost]
        public ActionResult SelectItem(CatalogueViewModel vm)
        {
            Dictionary<string, object> cart;
            if (HttpContext.Session.GetObject<Dictionary<String, Object>>(SessionVars.Cart) == null)
            {
                cart = new Dictionary<string, object>();
            }
            else
            {
                cart = HttpContext.Session.GetObject<Dictionary<string, object>>(SessionVars.Cart);
            }
            ProductViewModel[] catalogue = HttpContext.Session.GetObject<ProductViewModel[]>(SessionVars.Catalogue);
            String retMsg = "";
            foreach (ProductViewModel item in catalogue)
            {
                if (item.ProductId == vm.ProductId)
                {
                    if (vm.Qty > 0) // update only selected item
                    {
                        item.Qty = vm.Qty;
                        retMsg = vm.Qty + " - item(s) Added!";
                        cart[item.ProductId] = item;
                    }
                    else
                    {
                        item.Qty = 0;
                        cart.Remove(item.ProductId);
                        retMsg = "item(s) Removed!";
                    }
                    vm.GenreId = item.GenreId;
                    break;
                }
            }
            ViewBag.AddMessage = retMsg;
            HttpContext.Session.SetObject(SessionVars.Cart, cart);
            vm.SetGenres(HttpContext.Session.GetObject<List<Genre>>(SessionVars.Genres));
            return View("Index", vm);
        }
    }
}

ASPNetCase1/src/ASPNetCase1/Views/Genre/Index.cshtml
@model CatalogueViewModel
<div class="col-sm-2 col-xs-12">&nbsp;</div>
<div class="text-center col-sm-8 col-xs-12">
    <form id="genreForm" asp-controller="Genre" asp-action="SelectGenre" method="post" onload="this.form.submit();">
        <div class="col-sm-4 col-xs-12">&nbsp;</div>
        <div class="col-sm-4 col-xs-12" style="padding-bottom:5%;">
            <span style="font-size:medium;" class="title">Genres</span>
            <select asp-for="GenreId" asp-items="@Model.GetGenres()"
                    class="form-group form-control" onchange="this.form.submit();">
                <option selected style="display:none;">Select Genre</option>
            </select>
        </div>
        <div class="col-sm-4 col-xs-12">&nbsp;</div>
    </form>
    <catalogue genre="@Model.GenreId"></catalogue>@*All Summary information is sourced from www.GoodReads.com*@
</div>

<div class="modal" id="details_popup">
    <div class="modal-dialog">
        <div class="modal-content col-xs-12">
            <div class="modal-body">
                <a href="" style="font-size:xx-large" data-dismiss="modal" class="pull-right">X</a>
                <div class="text-center">
                    <img alt="" id="detailsGraphic" />
                    <h4 id="productName"></h4>
                </div>
                <form asp-controller="Genre" asp-action="SelectItem" method="post" role="form">
                    <table class="table table-striped">
                        <tr><td class="col-xs-2 col-sm-2 text-right">Author</td><td class="col-xs-8 col-sm-10 text-left" id="author"></td></tr>
                        <tr><td class="col-xs-2 col-sm-2 text-right">Genre</td><td class="col-xs-8 col-sm-10 text-left" id="genre"></td></tr>
                        <tr><td class="col-xs-2 col-sm-2 text-right">Description</td><td class="col-xs-8 col-sm-10 text-left" id="description"></td></tr>
                        <tr><td class="col-xs-2 col-sm-2 text-right">Publisher</td><td class="col-xs-8 col-sm-10 text-left" id="publisher"></td></tr>
                        <tr><td class="col-xs-2 col-sm-2 text-right">ISBN10</td><td class="col-xs-8 col-sm-10 text-left" id="isbn10"></td></tr>
                        <tr><td class="col-xs-2 col-sm-2 text-right">ISBN13</td><td class="col-xs-8 col-sm-10 text-left" id="isbn13"></td></tr>
                        <tr><td class="col-xs-2 col-sm-2 text-right">Price</td><td class="col-xs-8 col-sm-10 text-left" id="price"></td></tr>
                        <tr>
                            <td class="col-xs-4 text-right">Qty:</td>
                            <td class="col-xs-4 text-left">
                                <input asp-for="Qty" type="number" maxlength="3" size="3" min="0" style="width: 50px;" id="qty" />
                                <input asp-for="ProductId" type="hidden" id="detailsId" />
                            </td>
                        </tr>
                    </table>
                    <div class="text-center">
                        <button type="submit" class="btn btn-sm btn-primary" id="modalbtn">Add To Cart</button>
                        <button id="btnRemove" type="submit" class="btn-sm btn btn-danger">Remove Item</button>
                        <a href="/Cart" class="btn btn-sm btn-success">View Cart</a>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <div id="results" class="text-center">
                    @ViewBag.AddMessage
                </div>
            </div>
        </div><!--modal-content-->
    </div><!--modal-dialog-->
</div><!--modal-->