ASPNetCase1/src/ASPNetCase1/Models/Cart.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ASPNetCase1.Models
{
    public class Cart
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int CartId { get; set; }
        [Required]
        public string UserId { get; set; }
        [Required]
        public DateTime DateCreated { get; set; }
        [Required]
        public decimal TotalCostPrice { get; set; }
        [Required]
        public decimal TotalMSRP { get; set; }
        [Required]
        public decimal TotalTax { get; set; }

        [Column(TypeName = "timestamp")]
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        [MaxLength(8)]
        public byte[] Timer { get; set; }

    }
}

ASPNetCase1/src/ASPNetCase1/ViewModels/CartViewModel.cs
namespace ASPNetCase1.ViewModels
{
    public class CartViewModel
    {
        public int CartId { get; set; }
        public string UserId { get; set; }
        public string ProductName { get; set; }
        public decimal MSRP { get; set; }
        public int QtyS { get; set; }
        public int QtyO { get; set; }
        public int QtyB { get; set; }
        public decimal Extended { get; set; }

        public string DateCreated { get; set; }
        public decimal TotalCostPrice { get; set; }
        public decimal TotalMSRP { get; set; }
        public decimal TotalTax { get; set; }
        public decimal Total { get; set; }

    }
}

ASPNetCase1/src/ASPNetCase1/Controllers/CartController.cs
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Http;
using ASPNetCase1.Utils;
using ASPNetCase1.Models;
using System.Collections.Generic;
using System;
using System.Threading.Tasks;

namespace ASPNetCase1.Controllers
{
    public class CartController : Controller
    {

        AppDbContext _db;
        public CartController(AppDbContext context)
        {
            _db = context;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
        public ActionResult ClearCart()
        {
            HttpContext.Session.Remove(SessionVars.Cart); // clear out current cart
            HttpContext.Session.SetString(SessionVars.Message, "Cart Emptied"); // clear out current cart once order has been placed
            return Redirect("/Home");
        }

        // Add the tray, pass the session variable info to the db
        public ActionResult AddOrder()
        {
            // they can't add a Tray if they're not logged on
            if (HttpContext.Session.GetString(SessionVars.User) == null)
            {
                return Redirect("/Login");
            }
            CartModel model = new CartModel(_db);
            int retVal = -1;
            string retMessage = "";
            try
            {
                Dictionary<string, object> cartItems = HttpContext.Session.GetObject<Dictionary<string, object>>(SessionVars.Cart);
                retVal = model.AddCart(cartItems, HttpContext.Session.GetString(SessionVars.User));
                if (retVal > 0) // Cart Added
                {
                    retMessage = "Order " + retVal + " Created!";
                }
                else // problem
                {
                    retMessage = "Order not added, try again later";
                }
            }
            catch (Exception ex) // big problem
            {
                retMessage = "Order was not created, try again later! - " + ex.Message;
            }
            HttpContext.Session.Remove(SessionVars.Cart); // clear out current tray once persisted
            HttpContext.Session.SetString(SessionVars.Message, retMessage);
            return Redirect("/Home");
        }

        public IActionResult List()
        {
            if (HttpContext.Session.GetString(SessionVars.User) == null)
            {
                return Redirect("/Login");
            }
            return View("List");
        }
        [Route("[action]")]
        public IActionResult GetCarts()
        {
            CartModel model = new CartModel(_db);
            return Ok(model.GetCarts(HttpContext.Session.GetString(SessionVars.User)));
        }

        [Route("[action]/{cid:int}")]
        public IActionResult GetCartDetails(int cid)
        {
            CartModel model = new CartModel(_db);
            return Ok(model.GetCartDetails(cid, HttpContext.Session.GetString(SessionVars.User)));
        }
        [Route("[action]/{cid:int}")]
        public async Task<IActionResult> GetCartDetailsAsync(int cid)
        {
            CartModel model = new CartModel(_db);
            List<ViewModels.CartViewModel> details = await model.GetCartDetailsAsync(cid, HttpContext.Session.GetString(SessionVars.User));
            return Ok(details);
        }
    }
}

ASPNetCase1/src/ASPNetCase1/Views/Cart/Index.cshtml
<div class="col-sm-3">&nbsp;</div>
<div class="panel col-sm-6 col-xs-12">
    <div class="panel-title text-center" style="padding-top:20px;">
        <h3 style="font-weight:bolder" class="title">Order Items</h3>
        <img src="/img/cart.jpg" style="height:10%;width:10%;padding-bottom:5%;" />
    </div>
    <div class="text-center" style="padding-top:10px;">
        @{
            Dictionary<string, object> cart = Context.Session.GetObject<Dictionary<string, Object>>("cart");
            decimal GST = 0.13M;

            decimal subTotal = 0;
            decimal orderTax = 0;
            decimal orderTotal = 0;
            //Change all totals here later
        }
        <table class="table table-striped">
            <tr style="font-weight:bolder;">
                <th class="col-xs-2 text-center">Qty</th>
                <th class="col-xs-8 text-center">Product Name</th>
                <th class="col-xs-10 text-center">Price</th>
            </tr>
            @{
                if (cart != null)
                {
                    foreach (var key in cart.Keys)
                    {
                        ProductViewModel item = JsonConvert.DeserializeObject
                        <ProductViewModel>
                        (Convert.ToString(cart[key]));
                        if (item.Qty > 0)
                        {
                            subTotal += (item.MSRP * item.Qty);//Change original datatype to double? or make total decimal
                            <tr>
                                <td class="col-xs-2 text-center">@item.Qty</td>
                                <td class="col-xs-8 text-center">@item.ProductName</td>
                                <td class="col-xs-10 text-center">$@item.MSRP.ToString("N2")</td>
                            </tr>
                        }
                    }
                    orderTax = subTotal * GST;
                    orderTotal = subTotal + orderTax;
                }
            }
        </table>
        <hr />
        <table class="table table-striped">
            <tr><th colspan="4" class="col-xs-4 text-left" style="font-size:large;font-weight:bold;">Order Totals</th></tr>
            <tr>
                <td class="col-xs-2 text-right">Sub Total:</td>
                <td class="col-xs-4 text-left" id="subTotal">$@subTotal.ToString("N2")</td>
            </tr>
            <tr>
                <td class="col-xs-2 text-right">Tax:</td>
                <td class="col-xs-4 text-left" id="orderTax">$@orderTax.ToString("N2")</td>
            </tr>
            <tr>
                <td class="col-xs-2 text-right">Order Total:</td>
                <td class="col-xs-4 text-left" id="orderTotal">$@orderTotal.ToString("N2")</td>
            </tr>
        </table>
        <div class="text-center">
            <form asp-controller="Cart" asp-action="AddOrder" method="post" role="form">
                @if (Context.Session.GetString(SessionVars.User) != null)
                {
                    <button type="submit" class="btn btn-sm btn-primary" id="modalbtn">Add Order</button>
                }
                &nbsp;<a href="/Cart/ClearCart" class="btn btn-sm btn-success">Clear Cart</a>
            </form>
        </div>
    </div>
</div>

ASPNetCase1/src/ASPNetCase1/Views/Cart/List.cshtml
<div id="case"></div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.1.0/react.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.1.0/react-dom.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.23/browser.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react-bootstrap/0.29.4/react-bootstrap.min.js"></script>
<script type="text/babel" src="~/js/cartlist.jsx">
</script>
<script src="~/js/util.js"></script>